# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  username : postgres
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  username : postgres
  pool: 5
